// mock the api to load 20 products

const productsData = [
  {
    id: 1,
    title: "Summer Mug",
    price: 29.99,
    availability: "in_stock",
    rate: 4.5,
    photo: "./assets/summermug.jpg",
  },
  {
    id: 2,
    title: "Ball Mug",
    price: 69.99,
    availability: "new_arrival",
    rate: 5.0,
    photo: "./assets/ballmug.jpg",
  },
  {
    id: 3,
    title: "Shark Mug",
    price: 19.99,
    availability: "in_stock",
    rate: 4.5,
    photo: "./assets/sharkmug.jpg",
  },
  {
    id: 4,
    title: "Lama Mug",
    price: 39.99,
    availability: "sold_out",
    rate: 3.8,
    photo: "./assets/lamamug.jpg",
  },
  {
    id: 5,
    title: "Time Mug",
    price: 69.99,
    availability: "in_stock",
    rate: 5.0,
    photo: "./assets/timemug.jpg",
  },
  {
    id: 6,
    title: "Plan Mug",
    price: 39.99,
    availability: "sold_out",
    rate: 3.8,
    photo: "./assets/planmug.jpg",
  },
  {
    id: 7,
    title: "Girls Mug",
    price: 29.99,
    availability: "in_stock",
    rate: 4.5,
    photo: "./assets/girlsmug.jpg",
  },
  {
    id: 9,
    title: "Energie Mug",
    price: 49.99,
    availability: " last_items",
    rate: 3.8,
    photo: "./assets/energiemug.jpg",
  },
  {
    id: 10,
    title: "Pig Mug",
    price: 29.99,
    availability: "in_stock",
    rate: 1.5,
    photo: "./assets/pigmug.jpg",
  },
  {
    id: 11,
    title: "Espresso Mug",
    price: 39.99,
    availability: "sold_out",
    rate: 3.8,
    photo: "./assets/espressomug.jpg",
  },
  {
    id: 12,
    title: "Boss Mug",
    price: 29.99,
    availability: "in_stock",
    rate: 4.5,
    photo: "./assets/bossmug.jpg",
  },
  {
    id: 13,
    title: "Christmas Mug",
    price: 59.99,
    availability: "sold_out",
    rate: 5.0,
    photo: "./assets/christmasmug.jpg",
  },
  {
    id: 14,
    title: "Dad Mug",
    price: 19.99,
    availability: "in_stock",
    rate: 2.5,
    photo: "./assets/dadmug.jpg",
  },
  {
    id: 15,
    title: "Coffee Mug",
    price: 39.99,
    availability: "sold_out",
    rate: 3.8,
    photo: "./assets/coffeemug.jpg",
  },
  {
    id: 16,
    title: "Cat Mug",
    price: 19.99,
    availability: "in_stock",
    rate: 3.5,
    photo: "./assets/catmug.jpg",
  },
  {
    id: 17,
    title: "Blackcat Mug",
    price: 39.99,
    availability: "sold_out",
    rate: 3.8,
    photo: "./assets/blackcatmug.jpg",
  },
  {
    id: 18,
    title: "Yellowcat Mug",
    price: 29.99,
    availability: "in_stock",
    rate: 4.5,
    photo: "./assets/yellowcatmug.jpg",
  },
  {
    id: 19,
    title: "Box Mug",
    price: 39.99,
    availability: "sold_out",
    rate: 3.8,
    photo: "./assets/boxmug.jpg",
  },
  {
    id: 20,
    title: "Graycat Mug",
    price: 29.99,
    availability: "in_stock",
    rate: 4.5,
    photo: "./assets/graycatmug.jpg",
  },
];

export default productsData;
